site_name: Research Software Good Practice
nav:
  - Home: home.md  
  - Index: index.md        
  - Project:
    - 'Continuous Integration': 'good/cicd.md'
    - 'Version control': 'good/version.md'    
    - 'Packaging and deploying': 'good/packaging.md'
    - 'Using AI' : good/ai.md
  - Languages:
    - 'Python good practices': 'good/python.md'
  - Examples:
    - 'Making this streamlit webapp': 'examples/streamlit1.md'    
theme:
  name: material
  logo: assets/icr_svg_logo.svg  
  favicon: assets/icr_svg_logo.svg  
  palette:
    primary: pink  
    accent: deep orange  
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format